# Generated by Django 6.0 on 2025-12-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('delivered', 'Delivered'), ('processing', 'Processing')], default='pending', max_length=10),
        ),
    ]
